// Global comment

// Code generated by protoc-gen-desc. DO NOT EDIT.
// versions:
// - protoc-gen-desc v1.0.0
// - protoc             v4.25.3
// source: example.proto

// Package comment

package example_pkg

import (
	context "context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

import (
	_ "embed"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion7

//go:embed example.swagger.json
var swaggerJSON []byte

// SwaggerDef returns swagger definition for this package
func SwaggerDef() []byte {
	return swaggerJSON
}

// ExampleService1Description is the description struct for ExampleService1 service.
type ExampleService1Description struct {
	implementation ExampleService1Server
}

// NewExampleService1Description is description constructor method for ExampleService1 service.
func NewExampleService1Description(implementation ExampleService1Server) *ExampleService1Description {
	return &ExampleService1Description{implementation}
}

func (d *ExampleService1Description) RegisterGateway(ctx context.Context, mux *runtime.ServeMux) error {
	return RegisterExampleService1HandlerServer(ctx, mux, d.implementation)
}

func (d *ExampleService1Description) RegisterGRPC(server *grpc.Server) {
	RegisterExampleService1Server(server, d.implementation)
}

// ExampleService2Description is the description struct for ExampleService2 service.
type ExampleService2Description struct {
	implementation ExampleService2Server
}

// NewExampleService2Description is description constructor method for ExampleService2 service.
func NewExampleService2Description(implementation ExampleService2Server) *ExampleService2Description {
	return &ExampleService2Description{implementation}
}

func (d *ExampleService2Description) RegisterGateway(ctx context.Context, mux *runtime.ServeMux) error {
	return RegisterExampleService2HandlerServer(ctx, mux, d.implementation)
}

func (d *ExampleService2Description) RegisterGRPC(server *grpc.Server) {
	RegisterExampleService2Server(server, d.implementation)
}
